name: Deploy to Azure App Service
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'raise-genai'  # Replace with your app service name
          slot-name: 'production'  # Or use another slot if necessary
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # If using publish profile instead
