name: Deploy to Azure App Service
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'
          enable-AzPSSession: false
          environment: azurecloud
          auth-type: 'SERVICE_PRINCIPAL'  # Keep this as Service Principal
 
      - name: Set Azure Subscription
        run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
 
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'raise-genai'  # Replace with your app service name
          slot-name: 'production'  # Or use another slot if necessary
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # If using publish profile instead
