name: Deploy to Azure App Service
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Set your desired Python version here
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt   
 
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'raise-genai'  # Replace with your app service name
          slot-name: 'production'  # Or use another slot if necessary
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # If using publish profile instead

      - name: Set Startup Command
        run: |
          az webapp config set --name raise-genai --resource-group your-resource-group --startup-file "gunicorn --bind=0.0.0.0:8000 app:app"
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
