name: Build and deploy Node.js app to Azure Web App - raise-genai
 
on:
  push:
    branches:
      - feature
  workflow_dispatch:
 
jobs:
  build:
    runs-on: windows-latest
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.2.x'  # Fixed the Node.js version syntax
 
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
 
      - name: Compressing artifact for deployment
        run: Compress-Archive -Path .\build\* -DestinationPath raise-gen-ai.zip
     
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: raise-app
          path: raise-gen-ai.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
   
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: raise-app
     
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'raise-genai'
          slot-name: 'Production'
          package: raise-gen-ai.zip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # If using publish profile instead

          
